version: '3.9'
services:
  web:
    build: ./
    container_name: 'sh_newyear'
    restart :  always
    volumes: 
      - .:/new
    ports:
      - "8520:8520"
    env_file:
      - ./.env 
    command: sh -c "python manage.py runserver 0.0.0.0:8520"